version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quicknoise-production
    stdin_open: true
    tty: true
    links:
      - db
    ports:
      - '80:5000'
    environment:
      PORT: 5000
      NODE_ENV: production
      DB_HOST: 'db'
      DB_NAME: 'quicknoise'
      DB_USER: 'root'
      DB_PASS: 'example'

  db:
    image: mariadb:latest
    container_name: quicknoise-db-production
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: quicknoise
