version: '3.7'

services:
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: quicknoise-web
    command: ['npm', 'start']
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: development
      REACT_APP_API_PORT: 5000
      CHOKIDAR_USEPOLLING: 1

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile-development
    container_name: quicknoise-api
    command: ['npm', 'run', 'start-api']
    stdin_open: true
    tty: true
    links:
      - db-dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      NODE_ENV: development
      DB_HOST: 'db-dev'
      DB_USER: 'root'
      DB_PASS: 'example'

  db-dev:
    image: mariadb:latest
    container_name: quicknoise-db
    environment:
      MYSQL_ROOT_PASSWORD: example
